# -*- coding: utf-8 -*-
"""FacialExpression_TicTacToe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZK3X3WA2RaZjO_ZnWMNTk8TAaXGZRNM

**FACIAL EXPRESSION ANALYSIS**
"""

!pip install deepface opencv-python matplotlib -q
!pip install scikit-learn pandas -q

from deepface import DeepFace
import cv2
import matplotlib.pyplot as plt

# Load image from Colab files
img_path = "surprise.jpg"
image = cv2.imread(img_path)

if image is None:
    print("Error: face.jpg not found in Colab.")
else:

    # Analyze emotion
    result = DeepFace.analyze(
        img_path = img_path,
        actions = ['emotion'],
        enforce_detection=False
    )

    emotion = result[0]['dominant_emotion']
    emotions = result[0]['emotion']

    print("Emotion Scores:")
    for e,v in emotions.items():
        print(e,":", round(v,2))

    print("\nDominant Emotion Detected:", emotion)

    # Show image
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    plt.imshow(image_rgb)
    plt.title("Detected Emotion: " + emotion)
    plt.axis("off")
    plt.show()

"""**SENTIMENT ANALYSIS**"""

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load dataset from Colab files directly
data = pd.read_csv("sentiment_data.csv")

X = data['text']
y = data['sentiment']

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# TF-IDF
vectorizer = TfidfVectorizer(stop_words='english')
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Train model
model = LogisticRegression()
model.fit(X_train_vec, y_train)

# Predict
y_pred = model.predict(X_test_vec)

# Results
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

"""TIC TAC TOE"""

# Tic Tac Toe with UI Board (Google Colab)

from IPython.display import display, HTML, clear_output

board = [""] * 9
current_player = "X"

# Winning combinations
wins = [
    [0,1,2],[3,4,5],[6,7,8],
    [0,3,6],[1,4,7],[2,5,8],
    [0,4,8],[2,4,6]
]

def check_winner(player):
    for combo in wins:
        if all(board[i] == player for i in combo):
            return True
    return False

def draw_board():
    html = "<table style='border-collapse: collapse;'>"

    for r in range(3):
        html += "<tr>"
        for c in range(3):
            idx = r*3+c
            value = board[idx] if board[idx] != "" else "&nbsp;"

            html += f"""
            <td style='width:60px;height:60px;
            border:2px solid black;
            text-align:center;
            font-size:30px;
            cursor:pointer'
            onclick="google.colab.kernel.invokeFunction('notebook.play_move',['{idx}'],{{}})">
            {value}
            </td>
            """
        html += "</tr>"

    html += "</table>"

    display(HTML(html))


def minimax(is_maximizing):

    if check_winner("O"):
        return 1
    if check_winner("X"):
        return -1
    if "" not in board:
        return 0

    if is_maximizing:
        best_score = -100

        for i in range(9):
            if board[i] == "":
                board[i] = "O"
                score = minimax(False)
                board[i] = ""
                best_score = max(score,best_score)

        return best_score

    else:
        best_score = 100

        for i in range(9):
            if board[i] == "":
                board[i] = "X"
                score = minimax(True)
                board[i] = ""
                best_score = min(score,best_score)

        return best_score


def ai_move():

    best_score = -100
    move = None

    for i in range(9):
        if board[i] == "":
            board[i] = "O"
            score = minimax(False)
            board[i] = ""

            if score > best_score:
                best_score = score
                move = i

    board[move] = "O"


def play_move(index):

    global board

    index = int(index)

    if board[index] != "":
        return

    board[index] = "X"

    if check_winner("X"):
        clear_output()
        draw_board()
        print("You Win!")
        return

    if "" not in board:
        clear_output()
        draw_board()
        print("Draw!")
        return

    ai_move()

    if check_winner("O"):
        clear_output()
        draw_board()
        print("AI Wins!")
        return

    clear_output()
    draw_board()


from google.colab import output
output.register_callback('notebook.play_move', play_move)

draw_board()

## Explanation of AI Techniques and Integration

### 1. Facial Expression Analysis

*   **AI Technique**: This section utilizes **Deep Learning**, specifically pre-trained **Convolutional Neural Networks (CNNs)**, through the `DeepFace` library. DeepFace employs models that have been extensively trained on large datasets of facial images to recognize and classify various human emotions.
*   **Integration**: The `deepface` library is directly integrated into the code. The `DeepFace.analyze()` function abstracts the complexity of the underlying deep learning model, allowing for straightforward emotion detection by simply providing an image path. `OpenCV` (`cv2`) handles image loading and basic processing, while `matplotlib` is used for displaying the image and visualizing the detected emotion and its scores.

### 2. Sentiment Analysis

*   **AI Technique**: This project uses traditional **Machine Learning** for classification. The core algorithm is **Logistic Regression**, which is a linear model used for binary or multi-class classification tasks. Before applying Logistic Regression, **TF-IDF (Term Frequency-Inverse Document Frequency)** is used as a feature extraction technique to convert raw text into numerical representations.
*   **Integration**: The `scikit-learn` library is central to this integration:
    *   `TfidfVectorizer` transforms the text data (`X`) into a matrix of TF-IDF features, making it suitable for machine learning algorithms.
    *   `LogisticRegression` is then instantiated and trained (`model.fit()`) on these TF-IDF features and the corresponding sentiment labels (`y`).
    *   `train_test_split` ensures a robust evaluation by dividing the dataset into training and testing sets.
    *   `accuracy_score`, `classification_report`, and `confusion_matrix` are used to evaluate the model's performance.
    *   `pandas` is used for loading and managing the dataset.

### 3. Tic-Tac-Toe

*   **AI Technique**: The AI opponent in this game is implemented using a classic **Game Theory** algorithm known as the **Minimax Algorithm**. Minimax is a decision-making algorithm used in artificial intelligence, game theory, and economics to minimize the possible loss for a worst-case (maximum loss) scenario. It works by recursively exploring all possible future moves in the game tree to determine the optimal move for the current player, assuming the opponent also plays optimally.
*   **Integration**: The Minimax algorithm is implemented in the `minimax()` function, which recursively evaluates game states. The `ai_move()` function utilizes the `minimax` function to calculate the best possible move for the AI player. The game's user interface and interaction (clicking on cells) are handled through `IPython.display` for rendering HTML and `google.colab.output.register_callback` to link JavaScript events in the displayed HTML table to Python functions in the Colab kernel.