# -*- coding: utf-8 -*-
"""Friolo_FinHOA2_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NXkR3iChipFFbS5gtyjlgxQoHOr34LYh

*De La Salle University – Dasmariñas*  
*College of Information and Computer Studies*

*Computer Science Department*  
**S-CSIS426LA — SPECIAL TOPICS IN ARTIFICIAL INTELLIGENCE LAB**

# Finals Hands-on Activity No. 2 - Create and Simulate a 4-Level Game Tree

**Name 1:** Imperial, Luis Anton P.  
**Name 2:** Friolo, Christian C.  
**Section Code:** BCS42

**Date:** Wednesday, May 13, 2026  
**Instructor:** Ms. Marnelli B. Erquita

## Instructions:

- By pair.
- Create and simulate a 4-level game tree using any programming language.
- Your activity is good for 1 to 2 hours.
- Use MS Word for documentation and convert it into pdf.
- Include screenshots of your codes and output in your documentation.
- Filename: YourLastname_FinHOA2.pdf

### Part 1: Design your own game.

Instructions: Create a simple turn-based game that can be represented as a tree.

#### Requirements:

1. Two players:
    - MAX (AI)
    - MIN (opponent)
2. 4 Levels (Strict order):
    - Level 1: MAX
    - Level 2: MIN
    - Level 3: MAX
    - Level 4: MIN - Terminal nodes
3. Minimum of 9 terminal nodes.
4. Assign numerical values to terminal states
    - +10 = win
    - 0 = draw
    - -10 = lose
5. Output (Design)
    - Game Title
    - Rules
    - Drawn game tree

### Part 2: Represent the game tree in code

- Students must encode their tree using any language (python, java, C++)
- Students must create their own structure (>=leaves)
- Implement Minimax Algorithm
    - Task:
        - Write a function tree that:
            - Recursively evaluate the tree
            - Returns the best value for MAX
    - Required Output:
        - Final value of the root
        - Values of intermediate nodes.
- Implement Alpha-Beta Pruning
    - Task:
        - Modify minimax to include:
            - Alpha
            - Beta
            - Pruning condition: alpha >= Beta
    - Required output:
        - Final value (must match minimax)
        - Indication of pruned branches

## Game Tree
"""

import math

# 4-level game tree (Root → MIN → MAX → Terminal)
game_tree = [
    [  # MIN node (Level 2)
        [10, 0, -10],      # MAX node (Level 3)
        [0, -10, 10]
    ],
    [
        [-10, 10, 0],
        [10, 0, -10]
    ]
]

"""## Minimax Function"""

def minimax(node, depth, is_max):
    if depth == 0:
        return node

    if is_max:
        best = -math.inf
        for child in node:
            value = minimax(child, depth - 1, False)
            best = max(best, value)
        print(f"MAX node value: {best}")
        return best
    else:
        best = math.inf
        for child in node:
            value = minimax(child, depth - 1, True)
            best = min(best, value)
        print(f"MIN node value: {best}")
        return best

print("Minimax Result:")
minimax_result = minimax(game_tree, 3, True)
print("Final value at root:", minimax_result)

"""## Alpha-Beta Function"""

def alpha_beta(node, depth, alpha, beta, is_max):
    if depth == 0:
        return node

    if is_max:
        value = -math.inf
        for child in node:
            value = max(value, alpha_beta(child, depth - 1, alpha, beta, False))
            alpha = max(alpha, value)
            if alpha >= beta:
                print("Pruned at MAX node")
                break
        return value
    else:
        value = math.inf
        for child in node:
            value = min(value, alpha_beta(child, depth - 1, alpha, beta, True))
            beta = min(beta, value)
            if beta <= alpha:
                print("Pruned at MIN node")
                break
        return value

print("Alpha-Beta Result:")
ab_result = alpha_beta(game_tree, 3, -math.inf, math.inf, True)
print("Final value at root:", ab_result)

from collections import defaultdict, deque

class TreeNode:
    def __init__(self, val):
        self.val = val
        self.left = self.right = None

def vertical_order_traversal(root):
    result = []

    if not root:
        return result

    vertical_dict = defaultdict(list)

    queue = deque()
    distance_queue = deque()

    queue.append(root)
    distance_queue.append(0)

    while queue:
        current = queue.popleft()
        distance = distance_queue.popleft()

        vertical_dict[distance].append(current.val)

        if current.left:
            queue.append(current.left)
            distance_queue.append(distance - 1)

        if current.right:
            queue.append(current.right)
            distance_queue.append(distance + 1)

    for values in sorted(vertical_dict.items()):
        result.extend(values[1])

    return result[::-1]

root = TreeNode(1)
root.left = TreeNode(2)
root.right = TreeNode(3)
root.left.left = TreeNode(4)
root.left.right = TreeNode(5)
root.right.left = TreeNode(6)
root.right.right = TreeNode(7)
root.right.left.right = TreeNode(8)
root.right.right.right = TreeNode(9)

result = vertical_order_traversal(root)
print(result)