# -*- coding: utf-8 -*-
"""Tranportation_Model_Based_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovci6tT3xQwfmkBMBS44nN9FZA8dI8Rc
"""

# Transportation Model-Based Agent

trip_history = {}

def recommend_transport(distance, weather, traffic):

    key = (distance.lower(), weather.lower(), traffic.lower())

    # reuse previous decision if already experienced
    if key in trip_history:
        print("\nUsing previous experience...")
        return trip_history[key]

    distance = distance.lower()
    weather = weather.lower()
    traffic = traffic.lower()

    # Decision rules
    if distance == "short":
        if weather == "good":
            transport = "Walk"
        else:
            transport = "Tricycle"

    elif distance == "medium":
        if traffic == "heavy":
            transport = "Motorcycle"
        else:
            transport = "Tricycle"

    elif distance == "long":
        if traffic == "heavy":
            transport = "Motorcycle"
        else:
            transport = "Bus"

    else:
        transport = "Car"

    trip_history[key] = transport
    return transport


while True:

    print("\n--- Transportation Recommendation System ---")

    distance = input("Enter Distance (Short/Medium/Long): ")
    weather = input("Enter Weather (Good/Bad): ")
    traffic = input("Enter Traffic (Light/Heavy): ")

    result = recommend_transport(distance, weather, traffic)

    print("\nRecommended Transport:", result)

    print("\nTrip History:")

    for i, ((d, w, t), r) in enumerate(trip_history.items(), start=1):
        print(f"{i}. {d.capitalize()} + {w.capitalize()} + {t.capitalize()} = {r}")

    again = input("\nTry another trip? (yes/no): ")
    if again.lower() != "yes":
        break